default: &default
  adapter: postgresql
  encoding: utf-8
  pool: 5
  username: qix_dev
  password: 256391
  host: localhost
  port: 5432

development:
  <<: *default
  database: qix_db

test:
  <<: *default
  database: qix_db

production:
  <<: *default
  database: qix_db
